# Generated by Django 4.1.7 on 2023-02-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Number_store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField()),
                ("userid", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "Number_store",
            },
        ),
    ]
