# Generated by Django 4.1.7 on 2023-02-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main3", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="ExcelFiles")),
            ],
        ),
    ]
